### ISSUE TITLE
Issue with creating topics in capital letters  for multiple tables while using  debezium source connectors

### ISSUE THREAD

**Issue by hrish170** [debezium/debezium.github.io#1002]
Hi, I am trying to push my source postgres cdc changes to target oracle tables through kafka and that's why using debezium kafka source connector(docker image debezium/connect:1.8) as a source connector and kafka jdbc sink connector as a sink connector. along with kafka broker. Now, I want the topic names to be created in capital letters as otherwise we face other issues while creating the tables in oracle through the jdbc sink connector. As the postgres tables are by default created in small letters , I am using the below configurations in my source connector to create the topic in capital letters(hardcoding) and the below is working fine. Now, I want this to be done for multiple tables, "table.include.list": prodfxiapp1.requests,prodfxiapp1.trade,prodfxiapp1.leg. Is it possible to do it through the config changes? If so, what should be the changes?

"name": "source-connector",
  "config": {
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "tasks.max": "1",
    "database.hostname": "**",
    "database.port": "**",
    "database.user": "**",
    "database.password": "**",
    "database.dbname": "**",
    "database.server.name": "**",
    "table.include.list": "prodfxiapp1.requests",
    "transforms": "topicRename",
    "transforms.topicRename.type": "org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.topicRename.regex": "(.*)",
    "transforms.topicRename.replacement": "REQUESTS"
  }

**Comment by Naros** [comment]
Hi @hrish170, questions like this are best asked on our [mailing list](https://groups.google.com/forum/#!forum/debezium) or [Zulip chat](https://debezium.zulipchat.com/#narrow/stream/302529-users).  

That said, you can either use an SMT to upper-case the topic names as they are written to Kafka or an SMT to uppercase the topic names before they're converted to table names by the sink.  If you are using Debezium's JDBC sink connector, you can also write your own `TableNamingStrategy` implementation and apply the upper-case that way.  If you are using the Kafka JDBC sink connector, I don't believe they provide such a feature.

If you have any other questions, please direct those to one of the above linked spaces.
