### ISSUE TITLE
Error  in "database.hostname" SQL Server

### ISSUE THREAD

**Issue by yquintana** [debezium/debezium.github.io#1037]
HI, I have tried to make a connection through "sql server", through the host "localhost\SQLEXPRESS" but debezium eliminates the ''\" character and shows a connection error.

connect.json

database.hostname=localhost\SQLEXPRESS

ERROR:

Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 1 error(s):
Unable to connect. Check this and other connection properties. Error: The TCP/IP connection to the host localhostSQLEXPRESS, port 1433 has failed. Error: "localhostSQLEXPRESS. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`

**Comment by Naros** [comment]
Hi @yquintana, `database.hostname` is designed to only be a fully qualified host name or IP address, so in that context the `\` character makes no sense.  The content of `SQLEXPRESS` seems to indicate the name of the database, which would be placed into the `database.names` property.  You can see the [documentation ](https://debezium.io/documentation/reference/2.7/connectors/sqlserver.html) for more details.

If you have any other issues or problems, please raise those using our [Zulip](https://debezium.zulipchat.com/#narrow/stream/302529-users) or [mailing list](https://groups.google.com/forum/#!forum/debezium).  We don't use GitHub issues for support questions.
