### ISSUE TITLE
Set up CI and publication for migrated website

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#502]
In order to preview how the website looks like in the course of the migration, set up a GH Action which builds and publishes the website to somerepo.github.io. In the future, we should use this to publish a staged preview of the website before pushing changes to the live website.

**Comment by gunnarmorling** [comment]
@indraraj, assigning this to you, but please feel free to discuss and re-assign with @uidoyen and @mdrillin. Thx!

**Comment by gunnarmorling** [comment]
CC @uidoyen, as Indra is on PTO

**Comment by gunnarmorling** [comment]
A preview version currently is published to https://hubyahya.github.io/. Question is how to handle the CNAME file, so that pushing to that staging repo doesn't mess with the production site.

**Comment by gunnarmorling** [comment]
Hey @uidoyen, check this out re the CNAME file: https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-add-cname-file-cname. I.e. instead of having the CNAME file in the repo, it can be added on-the-fly by this GH Action for publishing the page (see pending PR https://github.com/debezium/debezium.github.io/pull/544/ by @ani-sha). That way, our approach with the staging repo should work.

**Comment by gunnarmorling** [comment]
Created a repo for staging purposes: https://github.com/debezium/staging.debezium.github.io.

**Comment by uidoyen** [comment]
@gunnarmorling Are we still going to do this?

**Comment by gunnarmorling** [comment]
Staging environment is set up now, see the README: https://github.com/debezium/debezium.github.io#6-publish-the-website

**Comment by gunnarmorling** [comment]
Done.
