### ISSUE TITLE
Move redundant footer from posts to template

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#551]
Atm. all the blog post AsciiDoc files have the same footer ("About Debezium", "Get Involved"). This should be extracted into the template. Might also go _under_ the author info actually.

@mdrillin @indraraj @uidoyen Here's a first follow-up improvement.

**Comment by mdrillin** [comment]
pending PR #558

**Comment by mdrillin** [comment]
merged, closing
