### ISSUE TITLE
Add latest posts side bar

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#552]
An area for improvement of the blog is discoverability of earlier posts. Right now, you only can go to older posts via the "Older" link at the bottom of the list page. To mitigate that, we added the "Featured Posts" section on the left some time ago, which is driven by the "Featured" tag assigned to posts. But it'd be nice to have some sort of "archive" side bar, as done on many blogs. Is here something like that in Jekyll we could use?

@mdrillin @indraraj @uidoyen

**Comment by indraraj** [comment]
Pr merged https://github.com/debezium/debezium.github.io/pull/581
