### ISSUE TITLE
Add support for Google Analytics

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#553]
As discussed with @uidoyen; I'd expect Jekyll has built-in support for GA and we just need to configure our tracking id somewhere. If so, the explicit tracker snippet should be removed from the Jekyll counterpart of the template linked below. The GA tracking should only be enabled for the production website.

**Comment by gunnarmorling** [comment]
This should also remove this legacy tracking code from the corresponding Jekyll template which isn't needed (or even working) any longer: https://github.com/debezium/debezium.github.io/blob/develop/_layouts/project.html.haml#L43-L46.

**Comment by gunnarmorling** [comment]
Ok, did a quick search and indeed it seems one needs to creates a custom include for the GA snippet and pull that into every page (or have this on the outer page frame template, if we have such thing). This post describes it quite well: https://desiredpersona.com/google-analytics-jekyll/.

**Comment by gunnarmorling** [comment]
@uidoyen, can we close this one by now?

**Comment by uidoyen** [comment]
https://github.com/debezium/debezium.github.io/pull/555 merged. Hence closing this.
