### ISSUE TITLE
Remove references to Awestruct from Rakefile

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#564]
@mdrillin @uidoyen @indra

**Comment by gunnarmorling** [comment]
Also, do we need docker-entrypoint.sh, now with the actual builder image in place?

**Comment by uidoyen** [comment]
> Also, do we need docker-entrypoint.sh, now with the actual builder image in place?

Dockerfile and docker-entrypoint.sh are not required now. We will be removing from website migration.

**Comment by uidoyen** [comment]
Closing in favor of https://github.com/debezium/debezium.github.io/pull/585
