### ISSUE TITLE
Ensure same spacing left and right in hero box

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#576]
See screenshot below, the spacing is a bit off. It's more equal on the current site, also the buttons and the text on the right hand side seem aligned there.

![Screen Shot 2020-11-23 at 17 26 38](https://user-images.githubusercontent.com/28612/99988099-87753980-2db1-11eb-8012-c4ce7f869f2f.png)

@mdrillin @indraraj @uidoyen

**Comment by indraraj** [comment]
mirrored the existing site https://github.com/debezium/debezium.github.io/pull/583

**Comment by indraraj** [comment]
Pr merged.
