### ISSUE TITLE
Incorrect label on prior stable releases

### ISSUE THREAD

**Issue by mdrillin** [debezium/debezium.github.io#578]
On the release details page, earlier releases show a label of 'latest stable' - even though they are not the latest stable.  Should just show 'stable' except for the real 'latest stable'

![releaseLabel](https://user-images.githubusercontent.com/1820403/100002374-18381f00-2d8a-11eb-9140-3159ac07e060.png)

**Comment by mdrillin** [comment]
Pending PR #580

**Comment by indraraj** [comment]
Pr merged.
