### ISSUE TITLE
Minimize generated HTML

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#586]
@mdrillin @uidoyen @indraraj I think with Awestruct we fed things through a miminizer (removing newlines etc.), if you look at the source of the current live website.

**Comment by mdrillin** [comment]
Added jekyll minifier plugin - minification kicks in for JEKYLL_ENV = 'production'.  Seemed to be working ok for my limited testing, would be good if someone else could test this.  On my laptop, this seemed to add about 2min to the build.

Pending PR #590

**Comment by mdrillin** [comment]
PR merged, closing
