### ISSUE TITLE
Do we need to commit content inside `bin/` ?

### ISSUE THREAD

**Issue by indraraj** [debezium/debezium.github.io#593]

**Comment by gunnarmorling** [comment]
Any insights? Can we exclude it?

**Comment by uidoyen** [comment]
@gunnarmorling @indraraj  We can remove `bin/` it is not required.

**Comment by gunnarmorling** [comment]
Ok, PR welcome :)

>

**Comment by indraraj** [comment]
PR merged https://github.com/debezium/debezium.github.io/pull/608
