### ISSUE TITLE
On specific version release page, documentation button link is incorrect

### ISSUE THREAD

**Issue by mdrillin** [debezium/debezium.github.io#595]
On the specific version release page, the documentation button always links to the latest stable version of the documentation.  It should link to the specific version, not the latest stable

![DocumentationButton](https://user-images.githubusercontent.com/1820403/100253467-c5d03d00-2f06-11eb-856c-37bc0a53a402.png)

**Comment by mdrillin** [comment]
pending PR #596

**Comment by gunnarmorling** [comment]
PR merged. Thx!
