### ISSUE TITLE
Disqus comments aren't loaded

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#599]
I pushed 9540910323db2e7318f680a7ec9b0a18973dcc1a as a work-around, hard-coding the base URL into the Disqus include for now.

That way, the comment widgets are loaded again, but ideally we won't have the base URL in any template/include. With Awestruct, the base URL was part of the environment-specific configuration and could be referenced in templates as a variable then. Is something similar doable for Jekyll?

@mdrillin @indraraj @uidoyen

**Comment by uidoyen** [comment]
@gunnarmorling Yes, It is doable. We can define `url:"https://debezium.io/"` in `_config.yml` and then it will be accessible as `{{site.url}}`

**Comment by gunnarmorling** [comment]
Sweet, thx! PR merged.
