### ISSUE TITLE
docs redirects not working

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#600]
Before we moved to Antora, there only was a single version published for the documentation, under the /docs path. With the old site, there used to be redirects for URLs like these:

https://debezium.io/docs/tutorial/
https://debezium.io/docs/online-resources/
https://debezium.io/docs/faq/
https://debezium.io/docs/connectors/postgresql/

They got lost in the transition to Jekyll. We should double-check with the old redirect configuration and add back all that are missing, so to keep any links out in the wild intact.

@mdrillin @uidoyen @indraraj

**Comment by gunnarmorling** [comment]
So it seems the trailing "/" is a problem. Those URLs worked with that before, whereas now they don't.

**Comment by indraraj** [comment]
yes, this issue seems to be with gh-pages.

**Comment by indraraj** [comment]
Pr raised https://github.com/debezium/debezium.github.io/pull/605

**Comment by gunnarmorling** [comment]
Done
