### ISSUE TITLE
Make corner pixels of Favicon transparent

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#601]
I know, I know, it's a super teeny-tiny detail, but can we make the lower left and the upper right pixel of the Favicon transparent? It doesn't look ideal with a dark browser theme atm.

![Screen Shot 2020-11-26 at 17 51 34](https://user-images.githubusercontent.com/28612/100376667-36af4c00-3010-11eb-9e77-d258b31f0623.png)

@mdrillin @indraraj @uidoyen

**Comment by indraraj** [comment]
Raised PR https://github.com/debezium/debezium.github.io/pull/603

**Comment by gunnarmorling** [comment]
Done.
