### ISSUE TITLE
Have consistent hover style in top-level menu

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/debezium.github.io#602]
When hovering over the Debezium logo, that tile gets a bit darker. That's not the case when hovering over any of the menu items ("Blog", "Community", etc.). This should be done consistently. The hover state should be a bit lighter than the active state when being e.g. on the blog URL.

**Comment by indraraj** [comment]
Raised pr https://github.com/debezium/debezium.github.io/pull/603

**Comment by gunnarmorling** [comment]
Done.
