### ISSUE TITLE
Missing step in kube (openshift) documentation: "connect" deployment

### ISSUE THREAD

**Issue by jotak** [debezium/debezium.github.io#616]
Hello,
I'm following the steps from that documentation https://debezium.io/documentation/reference/operations/openshift.html (adapting to my minikube environment)
It seems to me that a step is missing (or I am misunderstanding something), in step "3.c", it is described how to create an image for connect named `${DOCKER_ORG}/connect-debezium`, and shortly after stating we should see a pod 

```
debezium-connect-3-4sdjr                   1/1       Running       0          1m
```

... without describing how that pod is created, so I guess there's a missing step to create a deployment based on the built docker image, no?

**Comment by gunnarmorling** [comment]
Hi, yes, that step is missing indeed.

This docs page needs some love in general, that's tracked via https://issues.redhat.com/browse/DBZ-2594 already. I've added this info to that issue and will close this one here (as we use this repo's tracker only for DBZ UI related issues).

Thanks for reporting!

**Comment by gunnarmorling** [comment]
For reference, the step you're missing would look like described here: https://strimzi.io/blog/2020/01/27/deploying-debezium-with-kafkaconnector-resource/#create-the-connect-cluster

**Comment by jotak** [comment]
Thanks Gunnar!
