### ISSUE TITLE
Documentation links for 1.7 and 1.8 are broken

### ISSUE THREAD

**Issue by zdykstra** [debezium/debezium.github.io#744]
Following the [Documentation link](https://debezium.io/documentation/reference/1.7) from https://debezium.io/releases/1.7/ results in a 404. The same applies to https://debezium.io/documentation/reference/1.8 . 

The Documentation link from https://debezium.io/releases/1.6/ works, and then I'm able to jump to 1.7 via the menu footer. It takes me to https://debezium.io/documentation/reference/stable/index.html .

**Comment by gunnarmorling** [comment]
Thx, good catch. Indeed we're in the process of re-structuring how docs are published currently. This issue should be fixed now. Please let us know should you still encounter any issues.
