### ISSUE TITLE
the debezium document has one error--archive_log_target

### ISSUE THREAD

**Issue by datavoyagercn** [debezium/debezium.github.io#795]
in the following url:
https://debezium.io/documentation/reference/1.9/connectors/oracle.html
https://debezium.io/documentation/reference/stable/connectors/oracle.html

the follwing is wrong：
ALTER SYSTEM SET archive_log_target=1200 scope=both;

the following is correct ：
ALTER SYSTEM SET archive_lag_target=1200 scope=both;

archive_lag_target is the correct oracle  parameter，not archive_log_target！

**Comment by jpechane** [comment]
@datavoyagercn Thanks for the report. Could you please either create an issue in https://issues.redhat.com/projects/DBZ/summary or ideally provide a direct PR here? We don't use github to track issues.
Tahanks a lot.
